name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.x']
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: vendor
          key: ${{ runner.os }}-galaxy-${{ hashFiles('galaxy.yml') }}
      - run: ansible-galaxy install -r galaxy.yml
      - name: Check playbook syntax
        run: |
          ansible-playbook --syntax-check -e env=development deploy.yml
          ansible-playbook --syntax-check -e env=development dev.yml
          ansible-playbook --syntax-check -e env=development server.yml
          ansible-playbook --syntax-check -e env=development rollback.yml
          ansible-playbook --syntax-check -e xdebug_tunnel_inventory_host=1 xdebug-tunnel.yml
